//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOffice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopOffice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopOffice.
        /// </summary>
        public static string str_0001 {
            get {
                return ResourceManager.GetString("str_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pripojenie.
        /// </summary>
        public static string str_0002 {
            get {
                return ResourceManager.GetString("str_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlásenie.
        /// </summary>
        public static string str_0003 {
            get {
                return ResourceManager.GetString("str_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlásiť.
        /// </summary>
        public static string str_0004 {
            get {
                return ResourceManager.GetString("str_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásiť.
        /// </summary>
        public static string str_0005 {
            get {
                return ResourceManager.GetString("str_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užívateľ.
        /// </summary>
        public static string str_0006 {
            get {
                return ResourceManager.GetString("str_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string str_0007 {
            get {
                return ResourceManager.GetString("str_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string str_0008 {
            get {
                return ResourceManager.GetString("str_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť.
        /// </summary>
        public static string str_0009 {
            get {
                return ResourceManager.GetString("str_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno.
        /// </summary>
        public static string str_0010 {
            get {
                return ResourceManager.GetString("str_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string str_0011 {
            get {
                return ResourceManager.GetString("str_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadane meno alebo heslo je nesprávne.
        /// </summary>
        public static string str_0012 {
            get {
                return ResourceManager.GetString("str_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt s id {0} neexistuje.
        /// </summary>
        public static string str_0013 {
            get {
                return ResourceManager.GetString("str_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na sklade nie je dostatočné množstvo tovaru. Sklad obsahuje {0} položiek..
        /// </summary>
        public static string str_0014 {
            get {
                return ResourceManager.GetString("str_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód.
        /// </summary>
        public static string str_0015 {
            get {
                return ResourceManager.GetString("str_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov.
        /// </summary>
        public static string str_0016 {
            get {
                return ResourceManager.GetString("str_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množstvo.
        /// </summary>
        public static string str_0017 {
            get {
                return ResourceManager.GetString("str_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string str_0018 {
            get {
                return ResourceManager.GetString("str_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string str_0019 {
            get {
                return ResourceManager.GetString("str_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunikácia s pokladňou zlyhala: {0}.
        /// </summary>
        public static string str_0020 {
            get {
                return ResourceManager.GetString("str_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím čakajte....
        /// </summary>
        public static string str_0021 {
            get {
                return ResourceManager.GetString("str_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string str_0022 {
            get {
                return ResourceManager.GetString("str_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov.
        /// </summary>
        public static string str_0023 {
            get {
                return ResourceManager.GetString("str_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednotková cena.
        /// </summary>
        public static string str_0024 {
            get {
                return ResourceManager.GetString("str_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložiť.
        /// </summary>
        public static string str_0025 {
            get {
                return ResourceManager.GetString("str_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupnosť.
        /// </summary>
        public static string str_0026 {
            get {
                return ResourceManager.GetString("str_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string str_0027 {
            get {
                return ResourceManager.GetString("str_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty.
        /// </summary>
        public static string str_0028 {
            get {
                return ResourceManager.GetString("str_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridať produkt.
        /// </summary>
        public static string str_0029 {
            get {
                return ResourceManager.GetString("str_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obchod.
        /// </summary>
        public static string str_0030 {
            get {
                return ResourceManager.GetString("str_0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt s id {0} ešte nie je pridaný.
        /// </summary>
        public static string str_0031 {
            get {
                return ResourceManager.GetString("str_0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridať.
        /// </summary>
        public static string str_0032 {
            get {
                return ResourceManager.GetString("str_0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        public static string str_0033 {
            get {
                return ResourceManager.GetString("str_0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udalosť.
        /// </summary>
        public static string str_0034 {
            get {
                return ResourceManager.GetString("str_0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty.
        /// </summary>
        public static string str_0035 {
            get {
                return ResourceManager.GetString("str_0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predaj.
        /// </summary>
        public static string str_0036 {
            get {
                return ResourceManager.GetString("str_0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vložte požadovaný príkaz....
        /// </summary>
        public static string str_0037 {
            get {
                return ResourceManager.GetString("str_0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vložte hľadaný výraz....
        /// </summary>
        public static string str_0038 {
            get {
                return ResourceManager.GetString("str_0038", resourceCulture);
            }
        }
    }
}
